version: "3"
services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - proxy

  markpoint:
    build:
      context: ./MarkPoint
    restart: always
    ports:
      - "8080:8080"  # Optional, nur zum Testen
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
